version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - mynetwork

  client:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend
networks:
  mynetwork:
    driver: bridge