services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  client:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend
networks:
  mynetwork:
    driver: bridge