services:
  backend:
    image: xclaugod/backend:2.6
    ports:
      - "8800:8800"
    networks:
      - mynetwork

  client:
    image: xclaugod/client:1.1
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend
networks:
  mynetwork:
    driver: bridge