version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: booksLibrary
    depends_on:
      - mysql

  client:
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: production

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase

volumes:
  mysql-data:
