---

- hosts: CL_server
  become: true
  tasks:

    - name: Copy Kubernetes Manifests from GitHub
      copy:
        src: ../k8s/
        dest: /progetto/k8s/
        mode: "777"

    - name: Delete old services
      become: false
      shell: "kubectl delete -f /progetto/k8s/"

    - name: Apply Kubernetes Manifests
      become: false
      shell: "kubectl apply -f /progetto/k8s/"




    

    

