name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          cd backend
          ls -a
          docker build -t backend .
          docker tag backend ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push client Docker image
        run: |
          cd client
          docker build -t client .
          docker tag client ${{ secrets.DOCKER_USERNAME }}/client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/client:latest
          
      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          sudo apt install -y sshpass  # Installa sshpass per gestire la password della chiave SSH


      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY_PASSWORD }}" > ~/.ssh/password.txt
          chmod 600 ~/.ssh/password.txt

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
        run: |
            echo "${{ secrets.ANSIBLE_INVENTORY }}" > inventory.ini
            sshpass -e ansible-playbook -i inventory.ini ansible/deploy-stage.yml --private-key ~/.ssh/id_rsa --ask-pass --extra-vars "ansible_ssh_pass=$(cat ~/.ssh/password.txt)"
